# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jasontools

on:
  push:
    branches:
      - pre-release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_16a6dba6a8f24b65871fb211b91e9c74 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4684f7c92b8d40e795e36164722d6fa4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_16a6dba6a8f24b65871fb211b91e9c74 }}/mcr.microsoft.com/devcontainers/python:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jasontools'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b3a72619da84422ebf5720dd953cb0fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_16a6dba6a8f24b65871fb211b91e9c74 }}/mcr.microsoft.com/devcontainers/python:${{ github.sha }}'