# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jasontools

on:
  push:
    branches:
      - pre-release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a0c24180e14d44e9a220cb1afb9dab34 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_90551c24c91b408ca08e68efa3c84a6c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a0c24180e14d44e9a220cb1afb9dab34 }}/ubuntu-latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jasontools'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6cc90c0803b34b1ba81268b321a328fe }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a0c24180e14d44e9a220cb1afb9dab34 }}/ubuntu-latest:${{ github.sha }}'